# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [ ]:
# ВАШ КОД ЗДЕСЬ
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [2]:
# ВАШ КОД ЗДЕСЬ
x1 = [0 for i in range(10)]
x1[4]=1
print(x1)



[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [4]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x2 = x = np.arange(10, 50) #[i for i in range(10,50)]
x = np.array(x2)
x = x.reshape((-1,))
x3 = x[::-1]
x4 = x3[1::2]
x4

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [14]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x5 = [i for i in range(0,9)]
x5
x6 = np.array(x5).reshape(3,3)
x6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [2]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x1 = np.random.randint(0, 100, (3, 4, 2),dtype=int)

print(x1)
a = np.min(x1).item()
b = np.max(x1).item()
print(b)
a


[[[70 55]
  [98 12]
  [91 83]
  [92 52]]

 [[81 50]
  [86 39]
  [49 30]
  [18 49]]

 [[ 4 86]
  [94 44]
  [27 84]
  [48 91]]]
98


4

### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение.

In [6]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x = np.arange(1, 25)
A = x.reshape((6, 4))
B = np.ones((4, 3))
C = A@B
print(A)
print(B)
C

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[10., 10., 10.],
       [26., 26., 26.],
       [42., 42., 42.],
       [58., 58., 58.],
       [74., 74., 74.],
       [90., 90., 90.]])

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [8]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x = np.random.rand(7, 7)

print(x.mean())
print(np.std(x))
print(x/np.linalg.norm(x))
x


0.5128372797590588
0.28725491856717217
[[0.09227947 0.16333957 0.15931735 0.13338692 0.00360817 0.16473548
  0.01337836]
 [0.15949998 0.05864914 0.16049838 0.02359917 0.10888417 0.0147054
  0.10929812]
 [0.21531461 0.02139347 0.14102991 0.11902154 0.02967287 0.17999667
  0.18470213]
 [0.05969056 0.13168337 0.04828087 0.11875001 0.12511051 0.16289299
  0.22959742]
 [0.19527926 0.02753114 0.15685649 0.15331262 0.22877762 0.23392669
  0.04989306]
 [0.00727998 0.24073654 0.07765239 0.23229808 0.13506482 0.09402729
  0.24085417]
 [0.05376337 0.12656417 0.19087785 0.07091791 0.17206129 0.10052787
  0.18668758]]


array([[0.37969786, 0.6720854 , 0.65553536, 0.54884068, 0.01484636,
        0.67782908, 0.05504727],
       [0.65628682, 0.24132078, 0.66039486, 0.09710238, 0.4480204 ,
        0.06050758, 0.44972367],
       [0.88594453, 0.08802665, 0.58028892, 0.48973212, 0.12209351,
        0.74062353, 0.75998487],
       [0.24560583, 0.54183115, 0.19865897, 0.48861487, 0.51478615,
        0.67024785, 0.94471334],
       [0.80350609, 0.11328105, 0.64540977, 0.63082797, 0.94134014,
        0.96252675, 0.20529253],
       [0.02995458, 0.99054693, 0.31951251, 0.95582561, 0.55574465,
        0.3868895 , 0.99103092],
       [0.22121753, 0.52076745, 0.78539581, 0.29180246, 0.70797224,
        0.41363715, 0.76815429]])

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ