# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [ ]:
# ВАШ КОД ЗДЕСЬ
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [2]:
# ВАШ КОД ЗДЕСЬ
x1 = [0 for i in range(10)]
x1[4]=1
print(x1)



[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [7]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x2 = [i for i in range(10,50)]
x = np.array(x2)
x = x.reshape((-1,))
x3 = x[::-1]
x4 = x3[1::2]
x4

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [14]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x5 = [i for i in range(0,9)]
x5
x6 = np.array(x5).reshape(3,3)
x6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [29]:
# ВАШ КОД ЗДЕСЬ
import numpy as np
x = np.random.randint(0, 10, (3, 4, 2),dtype=int)

print(x1)
a = np.min(x1).item()
b = np.max(x1).item()
print(b)
a


[[[0 4]
  [4 3]
  [6 2]
  [4 0]]

 [[8 9]
  [0 9]
  [0 7]
  [7 6]]

 [[2 1]
  [9 0]
  [8 3]
  [8 6]]]


9

### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение.

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [ ]:
# ВАШ КОД ЗДЕСЬ

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ